# Site settings
title: AdamRMS
email: studios@jbithell.com
description:  Rental Management System
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://about.adam-rms.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
