name: Update Docusaurus Version
on:
  release:
    types: [published]
defaults:
  run:
    working-directory: docs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.5.0'
          cache: 'npm'
      - run: npm install
      - run: npm run docusaurus docs:version ${{ github.event.release.tag_name }}
      - uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          add: '.'
          default_author: github_actions
          message: 'Update docs to ${{ github.event.release.tag_name }}'
          push: true